name: 'rzk-check'
description: 'Check rzk formalisations'
inputs:
  rzk-version:
    description: 'Version of Rzk to use'
    required: false
    default: 'latest'
  files:  # files to check
    description: 'Files to check (*.rzk by default)'
    required: false
    default: '*.rzk'
runs:
  using: "composite"
  steps:
    - name: 🔨 Install rzk proof assistant
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: fizruk/rzk
        tag: ${{ inputs.rzk-version }}
        rename-to: rzk
        chmod: 0755

    - name: 🔨 Check rzk files
      shell: bash
      run: |
        rzk typecheck ${{ inputs.files }}
