name: 'rzk-check'
description: 'Check rzk formalisations'
inputs:
  files:  # files to check
    description: 'Files to check (*.rzk by default)'
    required: false
    default: '*.rzk'
runs:
  using: "composite"
  steps:
    - name: 🔨 Install rzk proof assistant
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: fizruk/rzk
        tag: v0.2.0

    - name: 🔨 Check rzk files
      shell: bash
      run: |
        rzk typecheck ${{ inputs.files }}
