name: 'rzk-check'
description: 'Check rzk formalisations'
inputs:
  files:  # files to check
    description: 'Files to check (*.rzk by default)'
    required: false
    default: '*.rzk'
runs:
  using: "composite"
  steps:
    - name: 🧰 Setup Stack
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true

    - name: 🔨 Install rzk proof assistant
      shell: bash
      run: |
        stack install rzk

    - name: 🔨 Check rzk files
      shell: bash
      run: |
        rzk typecheck ${{ inputs.files }}
